<a href="https://colab.research.google.com/github/natalia973/Data-Science-Data-Analytics/blob/main/pandasCleaningData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# üêº Pandas - Exerc√≠cios com `bios.csv`

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/sample_data/bios.csv")

### Exerc√≠cio 1
Mostre os nomes das colunas'

In [ ]:
df.columns.to_list()

['athlete_id',
 'name',
 'born_date',
 'born_city',
 'born_region',
 'born_country',
 'NOC',
 'height_cm',
 'weight_kg',
 'died_date']

### Exerc√≠cio 2
Verifique os tipos de dados de cada coluna

In [ ]:
df.dtypes

athlete_id        int64
name             object
born_date        object
born_city        object
born_region      object
born_country     object
NOC              object
height_cm       float64
weight_kg       float64
died_date        object
dtype: object

### Exerc√≠cio 4
Conte quantos valores nulos existem em cada coluna

In [ ]:
df.isnull().sum()

athlete_id           0
name                 0
born_date         1807
born_city        34592
born_region      34592
born_country     34592
NOC                  1
height_cm        38849
weight_kg        43430
died_date       111560
dtype: int64

### Exerc√≠cio 5
Copie o dataframe sem os valores nulos

In [ ]:
df_sem_nulos = df.dropna()
df_sem_nulos

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
107,108,Anders Nielsen,1967-02-24,Cape Town,Western Cape,RSA,Great Britain,173.0,70.0,2010-07-29
258,259,Tonny Maringgi,1959-06-10,Kendari,Sulawesi Tenggara,INA,Indonesia,167.0,65.0,2019-09-15
300,301,Jackson Fear,1978-01-13,Sydney,New South Wales,AUS,Australia,178.0,125.0,2006-07-21
...,...,...,...,...,...,...,...,...,...,...
135272,138435,Art Child,1916-09-15,West Ham,England,GBR,Great Britain,180.0,71.0,1996-06-30
135277,138440,Toyoko Yoshino,1920-02-12,Abashiri,Hokkaido,JPN,Japan,159.0,54.0,2015-01-24
135283,138446,Jacques Demar√©,1900-09-01,Vincennes,Val-de-Marne,FRA,France,185.0,78.0,1935-12-09
136653,139884,Johanna Bassani,2002-04-25,V√∂cklabruck,Ober√∂sterreich,AUT,Austria,163.0,54.0,2020-05-05
141190,144729,Naonobu Fujii,1992-01-05,Ishinomaki,Miyagi,JPN,Japan,183.0,80.0,2023-03-10

### Exerc√≠cio 6
Mostre o n√∫mero de valores √∫nicos em cada coluna

In [ ]:
df.nunique()

athlete_id      145500
name            142780
born_date        41279
born_city        22368
born_region       2554
born_country       236
NOC                696
height_cm           95
weight_kg          141
died_date        20009
dtype: int64

### Exerc√≠cio 7
Liste todas as colunas que cont√™m dados do tipo object

In [ ]:
df.select_dtypes(include='object').columns

Index(['name', 'born_date', 'born_city', 'born_region', 'born_country', 'NOC',
       'died_date'],
      dtype='object')

### Exerc√≠cio 8
Filtre todas as linhas onde a coluna 'height' > 180

In [ ]:
df[df['height_cm'] > 180 ]

In [ ]:
df.query('height_cm > 180')

In [ ]:
df.loc[df['height_cm'] > 180 ]

### Exerc√≠cio 9
Calcule o desvio padr√£o da coluna 'height'

In [ ]:
df['height_cm'].std()

10.380281757520233

### Exerc√≠cio 10
Encontre o valor m√≠nimo e m√°ximo de 'weight'

In [ ]:
df['height_cm'].min(),df['height_cm'].max()

(127.0, 226.0)

### Exerc√≠cio 11
Crie uma nova coluna chamada 'imc'

In [ ]:
df['imc'] = df['weight_kg'] / (df['height_cm'] / 100) ** 2
df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,imc
0,1,Jean-Fran√ßois Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,22.694019
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.0,76.0,1994-07-17,22.694019
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,22.675737
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,NaN
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,21.872423
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,23.030045
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,20.700817
145498,149225,Andr√© Foussard,1899-05-19,Niort,Deux-S√®vres,FRA,France,166.0,NaN,1986-03-18,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,NaN

### Exerc√≠cio 12
Arredonde a coluna 'imc'

In [ ]:
df['imc'] = df['imc'].round(2)
df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,imc
0,1,Jean-Fran√ßois Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,22.69
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.0,76.0,1994-07-17,22.69
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,22.68
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,NaN
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,21.87
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,23.03
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,20.70
145498,149225,Andr√© Foussard,1899-05-19,Niort,Deux-S√®vres,FRA,France,166.0,NaN,1986-03-18,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,NaN

### Exerc√≠cio 13
Preencha altura nula com a m√©dia

In [ ]:
df['height_cm'].fillna(df['height_cm'].mean())
df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,imc
0,1,Jean-Fran√ßois Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,176.333724,NaN,1960-10-02,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.000000,76.0,NaN,22.69
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.000000,76.0,1994-07-17,22.69
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.000000,64.0,1978-03-20,22.68
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,176.333724,NaN,1930-07-25,NaN
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.000000,61.0,NaN,21.87
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.000000,65.0,NaN,23.03
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.000000,55.0,NaN,20.70
145498,149225,Andr√© Foussard,1899-05-19,Niort,Deux-S√®vres,FRA,France,166.000000,NaN,1986-03-18,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,176.333724,NaN,2003-10-20,NaN

### Exerc√≠cio 14
Verifique duplicatas

In [ ]:
df.duplicated().any()

np.False_

### Exerc√≠cio 15
Remova duplicatas

In [ ]:
df.drop_duplicates()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,imc
0,1,Jean-Fran√ßois Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,176.333724,NaN,1960-10-02,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.000000,76.0,NaN,22.69
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.000000,76.0,1994-07-17,22.69
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.000000,64.0,1978-03-20,22.68
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,176.333724,NaN,1930-07-25,NaN
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.000000,61.0,NaN,21.87
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.000000,65.0,NaN,23.03
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.000000,55.0,NaN,20.70
145498,149225,Andr√© Foussard,1899-05-19,Niort,Deux-S√®vres,FRA,France,166.000000,NaN,1986-03-18,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,176.333724,NaN,2003-10-20,NaN

### Exerc√≠cio 16
Quantos t√™m peso acima da m√©dia

In [ ]:
df[df['weight_kg'] > df['weight_kg'].mean()].shape[0]

49081

### Exerc√≠cio 17
Correla√ß√£o entre vari√°veis

In [ ]:
corr = df.corr(numeric_only=True)
corr

            athlete_id  height_cm  weight_kg       imc
athlete_id    1.000000  -0.000310   0.005498  0.008394
height_cm    -0.000310   1.000000   0.779290  0.305614
weight_kg     0.005498   0.779290   1.000000  0.828709
imc           0.008394   0.305614   0.828709  1.000000

### Exerc√≠cio 18
Pessoa mais alta

In [ ]:
gigante = df[df['height_cm'] == df['height_cm'].max() ]
gigante

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,imc
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,27.61

### Exerc√≠cio 19
Nome em min√∫sculas

In [ ]:
df['name_lower'] = df['name'].str.lower()
df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,imc,name_lower
0,1,Jean-Fran√ßois Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,176.333724,NaN,1960-10-02,NaN,jean-fran√ßois blanchy
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.000000,76.0,NaN,22.69,arnaud boetsch
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.000000,76.0,1994-07-17,22.69,jean borotra
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.000000,64.0,1978-03-20,22.68,jacques brugnon
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,176.333724,NaN,1930-07-25,NaN,albert canet
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.000000,61.0,NaN,21.87,polina luchnikova
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.000000,65.0,NaN,23.03,valeriya merkusheva
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.000000,55.0,NaN,20.70,yuliya smirnova
145498,149225,Andr√© Foussard,1899-05-19,Niort,Deux-S√®vres,FRA,France,166.000000,NaN,1986-03-18,NaN,andr√© foussard
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,176.333724,NaN,2003-10-20,NaN,bill phillips

### Exerc√≠cio 20
N√∫mero de letras do nome

In [ ]:
df['name_characters'] = df['name'].str.len()
df

### Exerc√≠cio 21
√öltimas 5 linhas

In [ ]:
df.tail(5)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,imc,name_lower,name_characters
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.000000,61.0,NaN,21.87,polina luchnikova,17
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.000000,65.0,NaN,23.03,valeriya merkusheva,19
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.000000,55.0,NaN,20.70,yuliya smirnova,15
145498,149225,Andr√© Foussard,1899-05-19,Niort,Deux-S√®vres,FRA,France,166.000000,NaN,1986-03-18,NaN,andr√© foussard,14
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,176.333724,NaN,2003-10-20,NaN,bill phillips,13

### Exerc√≠cio 27
Salve novo CSV

In [ ]:
df.to_csv("dataframa_novo.csv",index=False)