<a href="https://colab.research.google.com/github/natalia973/Data-Science-Data-Analytics/blob/main/pandas_exercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# üêº Pandas - Exerc√≠cios com `bios.csv`

In [1]:
import pandas as pd
df=pd.read_csv('/content/bios (1).csv')

### Exerc√≠cio 1
Mostre os nomes das colunas'

### Exerc√≠cio 2
Verifique os tipos de dados de cada coluna

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

### Exerc√≠cio 4
Conte quantos valores nulos existem em cada coluna

In [21]:
df.isnull().sum()

athlete_id           0
name                 0
born_date         1807
born_city        34592
born_region      34592
born_country     34592
NOC                  1
height_cm            0
weight_kg        43430
died_date       111560
imc              43430
dtype: int64

### Exerc√≠cio 5
Copie o dataframe sem os valores nulos

In [19]:
df2 = df.dropna()
df2

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,imc
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.0,76.0,1994-07-17,0.002269
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,0.002268
107,108,Anders Nielsen,1967-02-24,Cape Town,Western Cape,RSA,Great Britain,173.0,70.0,2010-07-29,0.002339
258,259,Tonny Maringgi,1959-06-10,Kendari,Sulawesi Tenggara,INA,Indonesia,167.0,65.0,2019-09-15,0.002331
300,301,Jackson Fear,1978-01-13,Sydney,New South Wales,AUS,Australia,178.0,125.0,2006-07-21,0.003945
...,...,...,...,...,...,...,...,...,...,...,...
135272,138435,Art Child,1916-09-15,West Ham,England,GBR,Great Britain,180.0,71.0,1996-06-30,0.002191
135277,138440,Toyoko Yoshino,1920-02-12,Abashiri,Hokkaido,JPN,Japan,159.0,54.0,2015-01-24,0.002136
135283,138446,Jacques Demar√©,1900-09-01,Vincennes,Val-de-Marne,FRA,France,185.0,78.0,1935-12-09,0.002279
136653,139884,Johanna Bassani,2002-04-25,V√∂cklabruck,Ober√∂sterreich,AUT,Austria,163.0,54.0,2020-05-05,0.002032
141190,144729,Naonobu Fujii,1992-01-05,Ishinomaki,Miyagi,JPN,Japan,183.0,80.0,2023-03-10,0.002389

### Exerc√≠cio 6
Mostre o n√∫mero de valores √∫nicos em cada coluna

In [25]:
df.nunique()

athlete_id      145500
name            142780
born_date        41279
born_city        22368
born_region       2554
born_country       236
NOC                696
height_cm           96
weight_kg          141
died_date        20009
imc               3525
dtype: int64

### Exerc√≠cio 7
Liste todas as colunas que cont√™m dados do tipo object

In [26]:
df.select_dtypes(include='object').columns

Index(['name', 'born_date', 'born_city', 'born_region', 'born_country', 'NOC',
       'died_date'],
      dtype='object')

### Exerc√≠cio 8
Filtre todas as linhas onde a coluna 'height' > 180

In [17]:
df.loc[df['height_cm'] > 180]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,imc
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,0.002269
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.0,76.0,1994-07-17,0.002269
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,0.002137
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN,0.002212
25,26,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,NaN,0.002304
...,...,...,...,...,...,...,...,...,...,...,...
145465,149192,Stanislav Galiyev,1992-01-17,Moskva (Moscow),Moskva,RUS,ROC,188.0,82.0,NaN,0.002320
145466,149193,Mikkel Aagaard,1995-10-18,Frederikshavn,Nordjylland,DEN,Denmark,184.0,81.0,NaN,0.002392
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN,0.002774
145473,149200,Toms Andersons,1993-11-25,Rƒ´ga,Rƒ´ga,LAT,Latvia,185.0,86.0,NaN,0.002513
145494,149221,George Wright,1890-07-21,Toronto,Ontario,CAN,Canada,183.0,NaN,1973-01-28,NaN

### Exerc√≠cio 9
Calcule o desvio padr√£o da coluna 'height'

In [16]:
df['height_cm'].std()

8.887089781136993

### Exerc√≠cio 10
Encontre o valor m√≠nimo e m√°ximo de 'weight'

In [14]:
df['height_cm'].min()

127.0

In [15]:
df['height_cm'].max()

226.0

### Exerc√≠cio 11
Crie uma nova coluna chamada 'imc'

In [12]:
df['imc'] = df['weight_kg'] / df['height_cm'] ** 2
df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,imc
0,1,Jean-Fran√ßois Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,176.333724,NaN,1960-10-02,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.000000,76.0,NaN,0.002269
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.000000,76.0,1994-07-17,0.002269
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.000000,64.0,1978-03-20,0.002268
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,176.333724,NaN,1930-07-25,NaN
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.000000,61.0,NaN,0.002187
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.000000,65.0,NaN,0.002303
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.000000,55.0,NaN,0.002070
145498,149225,Andr√© Foussard,1899-05-19,Niort,Deux-S√®vres,FRA,France,166.000000,NaN,1986-03-18,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,176.333724,NaN,2003-10-20,NaN

### Exerc√≠cio 12
Arredonde a coluna 'imc'

In [13]:
df['imc'].round(6)

0              NaN
1         0.002269
2         0.002269
3         0.002268
4              NaN
            ...
145495    0.002187
145496    0.002303
145497    0.002070
145498         NaN
145499         NaN
Name: imc, Length: 145500, dtype: float64

### Exerc√≠cio 13
Preencha altura nula com a m√©dia

In [11]:
df['height_cm']=df['height_cm'].fillna(df['height_cm'].mean())
df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-Fran√ßois Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,176.333724,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.000000,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.000000,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.000000,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,176.333724,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.000000,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.000000,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.000000,55.0,NaN
145498,149225,Andr√© Foussard,1899-05-19,Niort,Deux-S√®vres,FRA,France,166.000000,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,176.333724,NaN,2003-10-20

### Exerc√≠cio 14
Verifique duplicatas

In [28]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
145495    False
145496    False
145497    False
145498    False
145499    False
Length: 145500, dtype: bool

### Exerc√≠cio 15
Remova duplicatas

In [10]:
df.drop_duplicates()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-Fran√ßois Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,Andr√© Foussard,1899-05-19,Niort,Deux-S√®vres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

### Exerc√≠cio 16
Quantos t√™m peso acima da m√©dia

In [9]:
df.loc[df['weight_kg'] > df['weight_kg'].mean()]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyr√©n√©es-Atlantiques,FRA,France,183.0,76.0,1994-07-17
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN
17,18,Jean-Philippe Gatien,1968-10-16,Al√®s,Gard,FRA,France,178.0,73.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145464,149191,Joonas N√§ttinen,1991-01-03,J√§ms√§,Keski-Suomi,FIN,Finland,189.0,90.0,NaN
145465,149192,Stanislav Galiyev,1992-01-17,Moskva (Moscow),Moskva,RUS,ROC,188.0,82.0,NaN
145466,149193,Mikkel Aagaard,1995-10-18,Frederikshavn,Nordjylland,DEN,Denmark,184.0,81.0,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145473,149200,Toms Andersons,1993-11-25,Rƒ´ga,Rƒ´ga,LAT,Latvia,185.0,86.0,NaN

### Exerc√≠cio 17
Correla√ß√£o entre vari√°veis

In [8]:
df.corr(numeric_only = True)

            athlete_id  height_cm  weight_kg
athlete_id    1.000000  -0.000378   0.005498
height_cm    -0.000378   1.000000   0.779290
weight_kg     0.005498   0.779290   1.000000

### Exerc√≠cio 18
Pessoa mais alta

In [7]:
df.loc[df['height_cm'].max(),'name']

'Ede T√≥th'

### Exerc√≠cio 19
Nome em min√∫sculas

In [6]:
df['name'].str.lower()

0         jean-fran√ßois blanchy
1                arnaud boetsch
2                  jean borotra
3               jacques brugnon
4                  albert canet
                  ...
145495        polina luchnikova
145496      valeriya merkusheva
145497          yuliya smirnova
145498           andr√© foussard
145499            bill phillips
Name: name, Length: 145500, dtype: object

### Exerc√≠cio 20
N√∫mero de letras do nome

In [29]:
df['quantidade_letras'] = df['name'].str.len()

### Exerc√≠cio 21
√öltimas 5 linhas

In [5]:
df.tail(5)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,Andr√© Foussard,1899-05-19,Niort,Deux-S√®vres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

### Exerc√≠cio 27
Salve novo CSV